### ISSUE TITLE
Question - Urql Devtools

### ISSUE THREAD

**Issue by denis-gorin** [lewebsimple/nuxt3-graphql#2]
Salut, merci pour un excellent paquet!
What about **Urql Devtools**, have you any plans to support include devtoolsExchange in urql Client exchanges list?

**Comment by lewebsimple** [comment]
Wow! I didn't even know urql devtools existed, of course I'll add support for this !!

The current plan is to support customizing the exchanges from `nuxt.config.ts` somehow. The difficulty lies in passing functions to the plugin runtime. So I might need to add some kind of config hooks.

This will also be the case for the codegen module, in the end I want to be able to inject codegen options from anywhere (so urql can add its introspection stuff for graphcache).

But it's a delicate balance between "it just works OOTB" and "customizable"

**Comment by denis-gorin** [comment]
I've been trying to handle with cache (similiar as Apollo Client cache) and suppose Urql Devtools could explain me where I am wrong, but although I see in Devtools `requestPolicy: "cache-first"`, the requests to query data run again and again when I returning to page

**Comment by lewebsimple** [comment]
Hum ... I don't have much time these days but I should work again on this project before december.
don't hesitate to send pull requests if you'd like to help in the meantime.

**Comment by lewebsimple** [comment]
Support for [urql devtools](https://github.com/lewebsimple/nuxt3-graphql/blob/a6cfa8c523e233f6374a1a35a87a324dae095572/packages/urql/src/plugin.ts#L12) has landed, though it might eventually sit behind a feature flag / module option eventually.
Maybe having it enabled by default in dev mode would be a good idea.
