### ISSUE TITLE
Question - Nuxt bridge support? 

### ISSUE THREAD

**Issue by gkweb** [lewebsimple/nuxt3-graphql#3]
Hey, Thanks for creating this. Can you confirm if this has Nuxt bridge support? Thanks

**Comment by lewebsimple** [comment]
It doesn't ATM but it will eventually. I plan on working on this project before mid-december, hopefully the documentation / examples for nuxt modules & bridge should have matured by then.

**Comment by lewebsimple** [comment]
As @urql/vue only support Vue 3 (see [this issue](https://github.com/FormidableLabs/urql/pull/2119) for progress), Nuxt bridge support looks kind of pointless for now.
